# Experiment configuration
name: "test_ms1_model"

# Data configuration
data:
  train_dir: "train_mzml"
  val_dir: "val_mzml"
  batch_size: 2000

# Model configuration
model:
  d_model: 256
  nhead: 8
  dim_feedforward: 512
  n_layers: 4
  dropout: 0.1
  n_bins: 1200
  bin_mz_min: 300
  bin_mz_max: 1500
  masked_peaks_fraction: 0.3
  
# Optimizer settings
optimizer:
  lr: 0.0005
  warmup_iters: 1000
  cosine_schedule_period_iters: 64000

# Training settings
training:
  checkpoint_path: "./train_checkpoints"
  max_epochs: 200
  gradient_clip_val: 5
  accelerator: "gpu"
  devices: 1
